##
## EPITECH PROJECT, 2017
## PSU_2018_malloc
## File description:
## Makefile
##

SRC	=	

OBJ	=	$(SRC:.cpp=.o)

NAME	=	groundhog

CFLAGS	=	-Wall -Wextra

all:	$(NAME)

$(NAME):
	cp groundhog.py $(NAME)

clean:

fclean: clean


re:	fclean all

.PHONY: all clean re fclean
